server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/filedb
    username: root
    password: yroot
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: faizuddinm378@gmail.com
    password: your_email_app_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

twilio:
  account_sid: AC91ca50c58fbc82088a939f5b0387d84e
  auth_token: 60e8ad522a01af9f476cce2562acb17d
  phone_number: 8790360347

upload:
  dir: uploads/
